# This workflow will install Python dependencies, (IN FUTURE) run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Build Matrix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  python_build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.0
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"
    - name: Install APT Dependencies (Linux)
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then sudo apt update; sudo apt install libasound2-dev -y fi
      shell: bash
    - name: Build/Export
      run: |
        shiv --site-packages fll_presenter -e main:main -o fll_presenter.pyz -r requirements.txt
    - uses: actions/upload-artifact@v3
      with:
        name: FLL Presenter ${{ matrix.os }}
        path: |
          ${{github.workspace}}/fll_presenter.pyz
        if-no-files-found: warn